"""Utility functions and classes for HLS transcoder."""

from hls_transcoder.utils.errors import (
    ConfigurationError,
    ErrorRecovery,
    FFmpegError,
    HardwareError,
    MediaInspectionError,
    NonRetryableError,
    ProcessTimeoutError,
    RecoveryAttempt,
    RecoveryConfig,
    RecoveryResult,
    RecoveryStrategy,
    RetryableError,
    TranscoderError,
    TranscodingError,
    ValidationError,
    create_hardware_fallback,
)
from hls_transcoder.utils.helpers import (
    calculate_aspect_ratio,
    calculate_segment_count,
    calculate_target_resolution,
    ensure_directory,
    format_bitrate,
    format_duration,
    format_size,
    get_file_size,
    get_quality_from_height,
    get_standard_resolutions,
    parse_bitrate,
    parse_time_to_seconds,
    sanitize_filename,
    should_include_quality,
)
from hls_transcoder.utils.logger import (
    get_active_monitor,
    get_logger,
    log_performance,
    set_active_monitor,
    setup_logger,
)

__all__ = [
    # Errors
    "ConfigurationError",
    "ErrorRecovery",
    "FFmpegError",
    "HardwareError",
    "MediaInspectionError",
    "NonRetryableError",
    "ProcessTimeoutError",
    "RecoveryAttempt",
    "RecoveryConfig",
    "RecoveryResult",
    "RecoveryStrategy",
    "RetryableError",
    "TranscoderError",
    "TranscodingError",
    "ValidationError",
    "create_hardware_fallback",
    # Logging
    "get_logger",
    "log_performance",
    "setup_logger",
    "set_active_monitor",
    "get_active_monitor",
    # Helpers
    "calculate_aspect_ratio",
    "calculate_segment_count",
    "calculate_target_resolution",
    "ensure_directory",
    "format_bitrate",
    "format_duration",
    "format_size",
    "get_file_size",
    "get_quality_from_height",
    "get_standard_resolutions",
    "parse_bitrate",
    "parse_time_to_seconds",
    "sanitize_filename",
    "should_include_quality",
]
